replicaCount: 1

app:
  name: demo
  namespace: default

image:
  repository: abdullohswe/demo
  tag: "b9d54536138bfc9a6abf19b9f82dee99aa92e623"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 30s
  scrapeTimeout: 10s

prometheus:
  enabled: false
  namespace: monitoring
  replicaCount: 1
  retention: 7d
  image:
    repository: prom/prometheus
    tag: v2.52.0
    pullPolicy: IfNotPresent
  service:
    port: 9090
    targetPort: 9090
    type: ClusterIP
  scrapeInterval: 15s
  scrapeTimeout: 10s
  resources: {}
