{{- if and .Values.prometheus (eq .Values.prometheus.enabled true) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}-prometheus
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    {{- include "demo.prometheusLabels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "demo.prometheusSelectorLabels" . | nindent 4 }}
{{- end }}
