{{- if and .Values.prometheus (eq .Values.prometheus.enabled true) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo.fullname" . }}-prometheus-config
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    {{- include "demo.prometheusLabels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
      scrape_timeout: {{ .Values.prometheus.scrapeTimeout }}
      evaluation_interval: 30s

    scrape_configs:
      - job_name: 'demo'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - {{ .Values.app.namespace }}

        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            action: keep
            regex: {{ include "demo.name" . }}

          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http

          - source_labels: [__meta_kubernetes_endpoint_address_target_name]
            target_label: pod

        metric_relabel_configs: []
  {{- end }}
