apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
