{{- if and .Values.serviceMonitor.enabled (not (and .Values.prometheus (eq .Values.prometheus.enabled true))) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "demo.fullname" . }}
  namespace: monitoring
  labels:
    release: monitoring
    {{- include "demo.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.app.namespace }}
  selector:
    matchLabels:
      {{- include "demo.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  {{- end }}
